name: Documentation Checks

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  check-documentation:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Check for broken links in markdown
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        config-file: '.github/markdown-link-check-config.json'
      continue-on-error: true
      
    - name: Spell check documentation
      uses: rojopolis/spellcheck-github-actions@0.36.0
      with:
        config_path: .github/spellcheck-config.yml
      continue-on-error: true
      
    - name: Check YAML files are valid
      run: |
        sudo apt-get install -y yamllint
        echo "Checking YAML files..."
        yamllint -d relaxed *.yml || echo "::warning::YAML issues found"
      continue-on-error: true
      
    - name: Verify all example files exist
      run: |
        echo "Verifying example files..."
        test -f .env.example || echo "::error::.env.example missing"
        test -f ansible_hosts.example.yml || echo "::error::ansible_hosts.example.yml missing"
        test -f PROJECT_INSTRUCTIONS.example.md || echo "::error::PROJECT_INSTRUCTIONS.example.md missing"
        echo "✅ Example files verified"
        
    - name: Check documentation completeness
      run: |
        echo "Checking documentation completeness..."
        test -f README.md || echo "::error::README.md missing"
        test -f SECURITY.md || echo "::error::SECURITY.md missing"
        test -f CONTRIBUTING.md || echo "::error::CONTRIBUTING.md missing"
        test -f LICENSE || echo "::error::LICENSE missing"
        test -f CHANGELOG.md || echo "::error::CHANGELOG.md missing"
        echo "✅ Core documentation files present"
        
    - name: Summary
      run: |
        echo "✅ Documentation checks completed!"
